# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: asim.neupane@rumsan.net
author_name: asim-office
contract_name: HelloWorld
preset_name: starter
project_name: rahat

